### ISSUE TITLE
Inclusion in the official OpenWRT repository.

### ISSUE THREAD

**Issue by paolosezart** [gSpotx2f/luci-app-internet-detector#10]
This is a great application. I use it to autorun fast reverse proxy (frpc) and write to a log file when there is an internet outage. Why is this application not in the official OpenWRT repository? I didn't find any similar analogues, and by the way it is a very handy application in cases when the internet is not stable and some programs are turned off. 
I have a request to the developer to send a request to include your development in the official OpenWRT repository.

**Comment by gSpotx2f** [comment]
>I have a request to the developer to send a request to include your development in the official OpenWRT repository.

Hi, I have no plans to add this application to the owrt repository. There is already a similar application - watchcat. Internet detector was created mainly as an example of using the luaposix and nixio libraries.
