### ISSUE TITLE
Отправка сообщения на Телеграм

### ISSUE THREAD

**Issue by dcbeelinekz2** [gSpotx2f/luci-app-internet-detector#12]
Хороший получился пакет у вас, а есть возможность скриптом отправлять в Телеграм сообщения внешнего ip, при перезагрузки роутера?
Можете поделиться как это сделать,?Спасибо

**Comment by gSpotx2f** [comment]
>а есть возможность скриптом отправлять в Телеграм сообщения внешнего ip, при перезагрузки роутера?

При перезагрузке - нет. Это приложение предназначено для проверки доступа в интернет (и действий при потере/восстановлении связи). Для выполнения скриптов после загрузки роутера, в OpenWrt есть другие механизмы (init, hotplug скрипты и т.п.).

**Comment by dcbeelinekz2** [comment]
А у вас будет такая вкладка Отправить в Телеграм, при потери и восстановлении связи или может привидете скрипт?
Спасибо за ответы

**Comment by gSpotx2f** [comment]
Модуля для тг не будет, потому что отравку сообщений в бот можно сделать shell-скриптом запускаемым из up-script (примеры тг скриптов [можно найти](https://bitbucket.org/padavan/rt-n56u/wiki/RU/%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9%20%D0%B2%20Telegram) в интернете).
