### ISSUE TITLE
OpenWrt 21.02.7 Problem install "luci-i18n-internet-detector-ru_1.3-0_all.ipk"

### ISSUE THREAD

**Issue by alexandrlastfm** [gSpotx2f/luci-app-internet-detector#13]
root@ARCHERC7:~# opkg install /tmp/luci-i18n-internet-detector-ru_1.3-0_all.ipk
Unknown package 'luci-i18n-internet-detector-ru'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-i18n-internet-detector-ru
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-i18n-internet-detector-ru found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-i18n-internet-detector-ru.

**Comment by gSpotx2f** [comment]
https://github.com/gSpotx2f/luci-app-log/issues/5#issuecomment-1825800345

**Comment by alexandrlastfm** [comment]
"Также можно просто вытащить из пакета файл локализации internet-detector.ru.lmo и положить его на роутере в папку /usr/lib/lua/luci/i18n." данный способ не помогает, может еще что то нужно скопировать из пакета?

**Comment by gSpotx2f** [comment]
>данный способ не помогает, может еще что то нужно скопировать из пакета?

ru локализация добавлена в системе? Обычно она уже должна быть, если ранее устанавливались другие пакеты локализации:

    uci set luci.languages.ru='Русский (Russian)'; uci commit luci

**Comment by alexandrlastfm** [comment]
Модель:  TP-Link Archer C7 v2
Архитектура: Qualcomm Atheros QCA9558 ver 1 rev 0
Целевая платформа: ath79/generic
Версия прошивки: OpenWrt 21.02.7 r16847-f8282da11e / LuCI openwrt-21.02 branch git-23.093.57360-e98243e
Версия ядра: 5.4.238

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\836D~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\836D~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


Имя пакета | Версия
-- | --
ath10k-board-qca988x | 20211216-1
ath10k-firmware-qca988x-ct | 2020-11-08-1
base-files | 1452-r16847-f8282da11e
busybox | 1.33.2-2
ca-bundle | 20211016-1
cgi-io | 2022-08-10-901b0f04-21
collectd | 5.12.0-10
collectd-mod-cpu | 5.12.0-10
collectd-mod-interface | 5.12.0-10
collectd-mod-iwinfo | 5.12.0-10
collectd-mod-load | 5.12.0-10
collectd-mod-memory | 5.12.0-10
collectd-mod-network | 5.12.0-10
collectd-mod-rrdtool | 5.12.0-10
curl | 7.83.1-4.1
dnsmasq-full | 2.85-9
dropbear | 2020.81-2
etherwake | 01.09.2005
firewall | 2021-03-23-61db17ed-1.1
fstools | 2021-01-04-c53b1882-1
fwtool | 2019-11-12-8f7fe925-1
getrandom | 2020-10-25-9ef88681-2
hostapd-common | 2020-06-08-5a8b3662-41
https-dns-proxy | 2021-11-22-3
internet-detector | 1.3.0-1
ip6tables | 1.8.7-1
ip-full | 5.11.0-3
ipset | 07.06.2001
iptables | 1.8.7-1
iptables-mod-ipopt | 1.8.7-1
iw | 5.9-8fab0c9e-3
jshn | 2021-05-16-b14c4688-2
jsonfilter | 2018-02-04-c7e938d6-1
kernel | 5.4.238-1-7fbe01f8…
kmod-ath | 5.4.238+5.10.168-1-1
kmod-ath10k-ct | 5.4.238+2021-09-22-e6a7d5b5-1
kmod-ath9k | 5.4.238+5.10.168-1-1
kmod-ath9k-common | 5.4.238+5.10.168-1-1
kmod-cfg80211 | 5.4.238+5.10.168-1-1
kmod-dma-buf | 5.4.238-1
kmod-gpio-button-hotplug | 5.4.238-3
kmod-hwmon-core | 5.4.238-1
kmod-i2c-core | 5.4.238-1
kmod-input-core | 5.4.238-1
kmod-ip6tables | 5.4.238-1
kmod-ipt-conntrack | 5.4.238-1
kmod-ipt-core | 5.4.238-1
kmod-ipt-ipopt | 5.4.238-1
kmod-ipt-ipset | 5.4.238-1
kmod-ipt-nat | 5.4.238-1
kmod-ipt-offload | 5.4.238-1
kmod-lib-crc-ccitt | 5.4.238-1
kmod-mac80211 | 5.4.238+5.10.168-1-1
kmod-mii | 5.4.238-1
kmod-nf-conntrack | 5.4.238-1
kmod-nf-conntrack6 | 5.4.238-1
kmod-nf-conntrack-netlink | 5.4.238-1
kmod-nf-flow | 5.4.238-1
kmod-nf-ipt | 5.4.238-1
kmod-nf-ipt6 | 5.4.238-1
kmod-nf-nat | 5.4.238-1
kmod-nfnetlink | 5.4.238-1
kmod-nf-reject | 5.4.238-1
kmod-nf-reject6 | 5.4.238-1
kmod-nls-base | 5.4.238-1
kmod-phy-ath79-usb | 5.4.238-1
kmod-ppp | 5.4.238-1
kmod-pppoe | 5.4.238-1
kmod-pppox | 5.4.238-1
kmod-slhc | 5.4.238-1
kmod-tun | 5.4.238-1
kmod-usb2 | 5.4.238-1
kmod-usb-core | 5.4.238-1
kmod-usb-ehci | 5.4.238-1
kmod-usb-ledtrig-usbport | 5.4.238-1
kmod-usb-net | 5.4.238-1
kmod-usb-net-cdc-ether | 5.4.238-1
kmod-video-core | 5.4.238-1
kmod-video-uvc | 5.4.238-1
kmod-video-videobuf2 | 5.4.238-1
libatomic1 | 8.4.0-3
libblobmsg-json20210516 | 2021-05-16-b14c4688-2
libbpf0 | 5.10.10-2
libc | 1.1.24-3
libcares | 1.17.2-1
libcurl4 | 7.83.1-4.1
libelf1 | 0.180-1
libev | 4.31-1
libgcc1 | 8.4.0-3
libgmp10 | 6.2.1-1
libgnutls | 3.7.1-2
libip4tc2 | 1.8.7-1
libip6tc2 | 1.8.7-1
libipset13 | 07.06.2001
libiwinfo20210430 | 2022-08-19-0dad3e66-1
libiwinfo-data | 2022-08-19-0dad3e66-1
libiwinfo-lua | 2022-08-19-0dad3e66-1
libjpeg-turbo | 2.0.6-1
libjson-c5 | 0.15-2
libjson-script20210516 | 2021-05-16-b14c4688-2
libltdl7 | 2.4.6-2
liblua5.1.5 | 5.1.5-9
liblucihttp0 | 2021-06-11-3dc89af4-1
liblucihttp-lua | 2021-06-11-3dc89af4-1
libmnl0 | 1.0.4-2
libnetfilter-conntrack3 | 1.0.8-1
libnettle8 | 03.06.2001
libnfnetlink0 | 1.0.1-4
libnghttp2-14 | 1.43.0-1
libnl-tiny1 | 2020-08-05-c291088f-2
libpthread | 1.1.24-3
librrd1 | 1.0.50-3
librt | 1.1.24-3
libtasn1 | 4.16.0-1
libubox20210516 | 2021-05-16-b14c4688-2
libubus20210630 | 2021-06-30-4fc532c8-2
libubus-lua | 2021-06-30-4fc532c8-2
libuci20130104 | 2021-04-14-4b3db117-5
libuci-lua | 2021-04-14-4b3db117-5
libuclient20201210 | 2023-04-13-007d9454-1
libusb-1.0-0 | 1.0.24-4
libustream-wolfssl20201210 | 2022-01-16-868fd881-2
libwolfssl5.5.3.99a5b54a | 5.5.3-stable-1
libxml2 | 2.9.14-1
libxtables12 | 1.8.7-1
logd | 2020-10-25-9ef88681-2
lua | 5.1.5-9
lua-bit32 | 5.3.0-1
luaposix | 35.0-1
luci | git-20.074.84698-ead5e81
luci-app-commands | git-21.099.45423-3fff72a
luci-app-firewall | git-22.089.67741-3856d50
luci-app-https-dns-proxy | 2021-09-27-3
luci-app-internet-detector | 1.3.0-r1
luci-app-mjpg-streamer | git-20.108.38431-8f34e10
luci-app-opkg | git-22.273.29015-e01e38c
luci-app-statistics | git-22.115.68435-0473e99
luci-app-vpn-policy-routing | 0.3.4-8
luci-app-wol | git-21.163.62608-7d7df07
luci-base | git-23.093.57360-e98243e
luci-compat | git-22.046.85744-f08a0f6
luci-i18n-base-ru | git-23.090.62029-650e6d2
luci-i18n-commands-ru | git-23.090.62029-650e6d2
luci-i18n-firewall-ru | git-23.090.62029-650e6d2
luci-i18n-https-dns-proxy-ru | git-23.090.62029-650e6d2
luci-i18n-mjpg-streamer-ru | git-23.090.62029-650e6d2
luci-i18n-opkg-ru | git-23.090.62029-650e6d2
luci-i18n-statistics-ru | git-23.090.62029-650e6d2
luci-i18n-vpn-policy-routing-ru | git-22.316.76471-782c7b6
luci-i18n-wol-ru | git-23.058.14609-a2350ac
luci-lib-base | git-20.232.39649-1f6dc29
luci-lib-ip | git-20.250.76529-62505bd
luci-lib-jsonc | git-22.097.61937-bc85ba5
luci-lib-nixio | git-20.234.06894-c4a4e43
luci-mod-admin-full | git-19.253.48496-3f93650
luci-mod-network | git-22.244.54918-77c916e
luci-mod-status | git-22.089.70019-d4f0b06
luci-mod-system | git-23.013.73129-aa7938d
luci-proto-ipv6 | git-21.148.49484-14511e5
luci-proto-openconnect | git-21.148.49484-9eee69a
luci-proto-ppp | git-21.163.64918-6c6559a
luci-theme-bootstrap | git-22.288.45155-afd0012
mjpg-streamer | 2019-05-24-1
mjpg-streamer-input-uvc | 2019-05-24-1
mjpg-streamer-output-http | 2019-05-24-1
mjpg-streamer-www-simple | 2019-05-24-1
mtd | 26
netifd | 2021-10-30-8f82742c-1
odhcp6c | 2021-01-09-53f07e90-16
odhcpd-ipv6only | 2021-07-18-bc9d317f-3
openconnect | 8.20-1
openwrt-keyring | 2021-02-20-49283916-2
opkg | 2021-06-13-1bf042dd-2
ppp | 2.4.8.git-2020-10-03-3
ppp-mod-pppoe | 2.4.8.git-2020-10-03-3
procd | 2021-03-08-2cfc26f8-2
resolveip | 2
rpcd | 2022-02-19-8d26a1ba-1
rpcd-mod-file | 2022-02-19-8d26a1ba-1
rpcd-mod-iwinfo | 2022-02-19-8d26a1ba-1
rpcd-mod-luci | 20210614
rpcd-mod-rrdns | 20170710
rrdtool1 | 1.0.50-3
swconfig | 12
uboot-envtools | 15.01.2021
ubox | 2020-10-25-9ef88681-2
ubus | 2021-06-30-4fc532c8-2
ubusd | 2021-06-30-4fc532c8-2
uci | 2021-04-14-4b3db117-5
uclient-fetch | 2023-04-13-007d9454-1
uhttpd | 2021-03-21-15346de8-2
uhttpd-mod-ubus | 2021-03-21-15346de8-2
urandom-seed | 3
urngd | 2020-01-21-c7f7b6b6-1
usb-modeswitch | 2017-12-19-f40f84c2-2
usign | 2020-05-23-f1f65026-1
vpnc-scripts | 20151220-2
vpn-policy-routing | 0.3.4-8
wireless-regdb | 2022.08.12-1
wpad-basic-wolfssl | 2020-06-08-5a8b3662-41
zlib | 1.2.11-6



</body>

</html>

**Comment by gSpotx2f** [comment]
Команда в консоли `uci set luci.languages.ru='Русский (Russian)'; uci commit luci` не включает перевод?
Поставил в виртуалке чистую 21.02.7, установил internet-detector и luci-app-internet-detector, скопировал файл `internet-detector.ru.lmo` в папку `/usr/lib/lua/luci/i18n`, ввёл в консоли `uci set luci.languages.ru='Русский (Russian)'; uci commit luci` и получил ru-перевод приложения, вообще без установки пакетов локализации.

**Comment by alexandrlastfm** [comment]
Не знаю, какое чудо произошло, но вчера у меня на всех устройствах тоже появился русский язык. Хотя ничего не делал, может кеш в браузерах каким то образом обновился?
