### ISSUE TITLE
Submit to main openwrt repo?

### ISSUE THREAD

**Issue by ShuttleTydirium** [gSpotx2f/luci-app-internet-detector#15]
Hello! Do you plan on ever submitting this to the main OpenWRT repository so that it can be included in the opkg repository?

It would be great if you did because then I wouldn't have to manually re-install the package every time I upgrade to a new snapshot build.

Thanks.

**Comment by gSpotx2f** [comment]
Hi! This project is still under development. It's an example of using the luaposix library, there was no goal to submit it to the official repository.

BTW, a similar application watchcat is already in the OpenWrt repository.
