### ISSUE TITLE
Email notification not work

### ISSUE THREAD

**Issue by ziiiiiiiii** [gSpotx2f/luci-app-internet-detector#16]
I set up email noti when internet connected or disconnected but there is no email was sent.

I run command mailsend in ssh succesfully.

please help me to use email notiication feature.

thank you

**Comment by gSpotx2f** [comment]
I checked mod-email, it works for me without errors. Maybe the problem is in a specific mail server. Try using the mailsend command in user scripts instead of mod-email.

**Comment by PaWill68** [comment]
Тоже не удалось заставить работать с яндексом
Адрес почтового сервера — smtp.yandex.ru.
Защита соединения — SSL.
Порт — 465
