### ISSUE TITLE
Incorrectly displayed form.

### ISSUE THREAD

**Issue by 4IceG** [gSpotx2f/luci-app-internet-detector#4]
Hi :), I don't know if it's just for me, but the controls are shifted, as if they did not fit.

I still have a question. Can I add my own AT command to reset the modem in the application?
@gSpotx2f And a little bit of privacy .. would you look at the code of my application? because I don't know how to work around a certain thing in LuCI JS.
![Internet detector](https://user-images.githubusercontent.com/59826889/153921403-4f594da6-cd72-4471-bc59-6f66e6c1cfa5.png)
.

**Comment by gSpotx2f** [comment]
[UI fixes](https://github.com/gSpotx2f/luci-app-internet-detector/commit/7a879809c7dc0b90cf22432915c7912aa6484772).
If you need more custom commands, you can restart modem in `User scripts` -> `down-script`. Something like this:

	mmcli -m any --command=AT+<command>
	/etc/init.d/modemmanager restart

I don't know much about modems. I just stole commands from watchcat :)

**Comment by 4IceG** [comment]
Ok, thanks for the hint :) I'll check it, although I don't use a modem manager.

@gSpotx2f gSpotx2f and could you take a look at my code in LuCI JS, my application and direct me to the solution?
I wrote a simple app, but I'd like to improve it even more.
