### ISSUE TITLE
Скорее вопрос, поскольку внятного ответа найти не могу

### ISSUE THREAD

**Issue by Yurannich2** [gSpotx2f/luci-app-internet-detector#8]
Есть платформа APU2C4 (OpenWrt 22.03.3) на ней установлены светодиоды, подгружаемые ядром (ими можно управлять из LuCI) и на ней-же есть NCT5104D и ей приходится управлять строками типа: 
echo 0 > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio0/direction
echo "1" > /sys/class/gpio/gpio0/value

Подскажите пожалуйста возможно ли добавить управление диодами в вэб интерфейс или это слишком сложно и требуется что-то делать с ядром системы? Заранее спасибо и спасибо за ваши труды: мониторинг дисков, сети и процессора то, чего мне действительно не хватало!

**Comment by gSpotx2f** [comment]
Смотря какое управление вам нужно. Вернее, индикацию каких событий вы хотите повесить на диоды. Если управление диодами сводится лишь к включению/выключению и т.п. (т.е. к записи значений в файлы в sysfs), то можно запилить своё приложение для LuCI. Если же вы хотите повесить на свои диоды те же триггеры (активность сетевого интерфейса и пр.), что и для стандартных диодов которые доступны OpenWrt (в /sys/class/leds), то тут я не в курсе... Попробуйте спросить [здесь](https://forum.openwrt.org/c/devel/).

**Comment by Yurannich2** [comment]
Спасибо большое!
